import { InstanceType } from '@octokit/rest';
import { RetryOctokit, executeWithRetry } from '../core/auth';

export async function createPullRequest(
  octokit: InstanceType<typeof RetryOctokit>,
  owner: string,
  repo: string,
  title: string,
  base: string,
  head: string,
  body?: string,
  draft = false
): Promise<any> {
  return executeWithRetry(async () => {
    const pr = await octokit.pulls.create({
      owner,
      repo,
      title,
      base,
      head,
      body: body || `Generated by Pi Coding Agent`,
      draft
    });
    return {
      url: pr.data.html_url,
      number: pr.data.number,
      state: pr.data.state,
      draft: pr.data.draft
    };
  });
}